version: '2.0'
services:
    app:
        container_name: mapa-de-area-react
        build: .
        volumes:
            - '.:/app'
            - '/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development